---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Find files
      ansible.builtin.find:
        path: '{{ redmine_file_dir }}'
      register: file_list

    - name: Show files
      ansible.builtin.debug:
        var: file_list

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
